name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: mattnotmitt/doxygen-action@1.9.8
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
